version: '3.7'

services:
  postgrescrescer:
    image: postgres:16
    container_name: postgres-crescer
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin4crescer:
    image: dpage/pgadmin4:8
    container_name: pgadmin-crescer
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5050:80"

volumes:
  postgres-data: